name = "files"
main = "index.ts"
compatibility_date = "2023-11-21"

[vars]
VERSION = "Files v0.2.1"

[[r2_buckets]]
binding = "files"
bucket_name = "files"

[[r2_buckets]]
binding = "assets"
bucket_name = "assets"
